name = "Oscar Vermolen"
description = "Verbindend denker en doener."
keywords = "Oscar Vermolen, manager, informatietechnologie, it, gadgets, Amersfoort"
image = "oscar_grijze_achtergrond.webp"
theme = "light"
primary_color = "#d81b60"
text_align = "center"
base_url = "https://oduboevi.github.io/jake"

[[sections]]
title = "Socials"
description = "Look for me on these websites"
direction = "column"
item_style = "filled"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/jakegyllenhaal"
[[sections.items]]
title = "IMDb"
url = "https://www.imdb.com/name/nm0350453/"
[[sections.items]]
title = "Wikipedia"
url = "https://en.wikipedia.org/wiki/Jake_Gyllenhaal"
[[sections.items]]
title = "Rotten Tomatoes"
url = "https://www.rottentomatoes.com/celebrity/jake_gyllenhaal"
