name = "Oscar Vermolen"
description = "Verbindend persoon"
keywords = "Oscar Vermolen, manager, informatietechnologie, it, gadgets, Amersfoort"
image = "oscar_blurred_achtergrond.webp"
theme = "dark"
primary_color = "#0A66C2"
text_align = "center"
base_url = "https://oduboevi.github.io/jake"

[[sections]]
title = "Contact"
description = "Op meerdere manieren ben ik te benaderen"
direction = "column"
item_style = "outline"

[[sections.items]]
title = "LinkedIn"
url = "https://www.linkedin.com/in/vermolen/"
[[sections.items]]
title = "Email"
url = "mailto:contact@oscarmail.eu"
[[sections.items]]
title = "Signal"
url = "https://signal.me/#eu/wcb2D8I4NuQqLB-Mf7VXizbM8DblaDMHGeTJzWWtF4uffSX9N8BBqKu9lgBnwSeD"
[[sections.items]]
title = "Telegram"
url = "https://t.me/oscarvermolen"
[[sections.items]]
title = "Mastodon"
url = "https://mastodon.social/@vermolen"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/oscarvermolen/"
[[sections.items]]
title = "Spotify"
url = "https://open.spotify.com/user/31wfob5veqrhrckmc5pogxaoiruy?si=tuOW8gqpTd6fHWLJ_0PW3w"
[[sections.items]]
title = "Website"
url = "https://www.oscarvermolen.nl"
